/**
 * Remove seeded and simulated accounts, leaving real wallets alone.
 *
 * Test data accumulates: fake users from the seed whose addresses nobody
 * controls, and bot wallets from `simulate:auction`. They clutter every list and
 * make a demo confusing.
 *
 * Dry run by default, because this deletes provenance. Nothing is removed
 * without `--apply`.
 *
 * Deliberately targeted by name rather than "delete everything except X": an
 * exclusion list silently grows to include real accounts as new ones appear,
 * whereas an inclusion list can only ever remove what it names.
 *
 *   npm run purge:test                          # report
 *   npm run purge:test -- --apply               # do it
 *   npm run purge:test -- --events a,b --apply  # also drop named events
 *
 * Named events are removed WITH their tickets. Those NFTs keep existing in
 * whoever's wallet holds them — we cannot burn someone else's token — so the
 * holder is left with a collectible HubWorld no longer recognises. Only do this
 * for events whose tickets you hold yourself.
 */
import { prisma } from '../src/prisma.js'
import { env } from '../src/env.js'
import { disconnectLedger, brokerCancelOffers } from '../src/ledger.js'

const APPLY = process.argv.includes('--apply')

/** Seeded fixtures — real-looking addresses that no one holds the keys to. */
const SEEDED = ['stationsquare', 'majula', 'peachcastle']
/** Wallets generated by simulate:auction, whose seeds lived only in that run. */
const SIM_PREFIX = 'sim-'

/** Extra events to drop, named explicitly — never inferred. */
const EXTRA_EVENTS = (() => {
  const i = process.argv.indexOf('--events')
  if (i === -1) return []
  return (process.argv[i + 1] ?? '').split(',').map((s) => s.trim()).filter(Boolean)
})()

async function main() {
  if (env.NODE_ENV === 'production') {
    console.error('Refusing to purge in production.')
    process.exit(1)
  }

  const users = await prisma.user.findMany({
    where: { OR: [{ username: { in: SEEDED } }, { username: { startsWith: SIM_PREFIX } }] },
    select: { id: true, username: true },
  })
  const userIds = users.map((u) => u.id)

  if (users.length === 0 && EXTRA_EVENTS.length === 0) {
    console.log('Nothing to purge.')
    return
  }

  // Events belonging to those accounts go too, but ONLY if no real account has
  // a ticket for them — deleting an event out from under someone's ticket would
  // destroy a stranger's provenance.
  const candidateEvents = await prisma.event.findMany({
    where: {
      OR: [{ organizerId: { in: userIds } }, { slug: { in: EXTRA_EVENTS } }],
    },
    select: {
      id: true,
      slug: true,
      tickets: { select: { id: true, ownerId: true, nfTokenId: true } },
    },
  })

  const eventsToDelete = candidateEvents.filter(
    (e) =>
      EXTRA_EVENTS.includes(e.slug) ||
      e.tickets.every((t) => t.ownerId === null || userIds.includes(t.ownerId)),
  )
  const eventsKept = candidateEvents.filter((e) => !eventsToDelete.includes(e))
  const eventIds = eventsToDelete.map((e) => e.id)

  console.log(APPLY ? 'purging test data\n' : 'dry run — nothing will be deleted\n')
  console.log(`accounts (${users.length}):`)
  for (const u of users) console.log(`  @${u.username}`)
  console.log(`\nevents (${eventsToDelete.length}):`)
  for (const e of eventsToDelete) console.log(`  ${e.slug} — ${e.tickets.length} ticket(s)`)
  for (const e of eventsKept) {
    console.log(`  ${e.slug} — KEPT, a real account holds a ticket for it`)
  }

  if (!APPLY) {
    console.log('\nRe-run with --apply to delete.')
    return
  }

  // Cancel any offers those simulated wallets left on-ledger. They are inert —
  // only the broker can match them — but they hold reserves and would linger
  // with no database record explaining them.
  const orphanOffers = await prisma.bid.findMany({
    where: { bidderId: { in: userIds }, buyOfferIndex: { not: null } },
    select: { buyOfferIndex: true },
  })
  const sellOffers = await prisma.listing.findMany({
    where: { sellerId: { in: userIds }, offerIndex: { not: null } },
    select: { offerIndex: true },
  })
  const indexes = [
    ...orphanOffers.map((b) => b.buyOfferIndex!),
    ...sellOffers.map((l) => l.offerIndex!),
  ]
  if (indexes.length > 0) {
    try {
      await brokerCancelOffers(indexes)
      console.log(`\ncancelled ${indexes.length} on-ledger offer(s)`)
    } catch {
      console.log('\ncould not cancel on-ledger offers (harmless — they are inert)')
    }
  }

  // Foreign keys dictate the order: children before parents.
  const ticketWhere = { OR: [{ ownerId: { in: userIds } }, { eventId: { in: eventIds } }] }

  const counts = await prisma.$transaction(async (tx) => {
    const bids = await tx.bid.deleteMany({
      where: { OR: [{ bidderId: { in: userIds } }, { auction: { ticket: ticketWhere } }] },
    })
    const auctions = await tx.auction.deleteMany({ where: { ticket: ticketWhere } })
    const listings = await tx.listing.deleteMany({
      where: { OR: [{ sellerId: { in: userIds } }, { buyerId: { in: userIds } }, { ticket: ticketWhere }] },
    })
    const gifts = await tx.gift.deleteMany({
      where: { OR: [{ fromId: { in: userIds } }, { toId: { in: userIds } }, { ticket: ticketWhere }] },
    })
    const redemptions = await tx.redemption.deleteMany({
      where: {
        OR: [
          { holderId: { in: userIds } },
          { staffId: { in: userIds } },
          { eventId: { in: eventIds } },
          { ticket: ticketWhere },
        ],
      },
    })
    const transfers = await tx.transfer.deleteMany({ where: { ticket: ticketWhere } })
    const tickets = await tx.ticket.deleteMany({ where: ticketWhere })
    const mints = await tx.mintRequest.deleteMany({
      where: { OR: [{ requestedById: { in: userIds } }, { eventId: { in: eventIds } }] },
    })
    const staff = await tx.eventStaff.deleteMany({
      where: {
        OR: [{ userId: { in: userIds } }, { addedById: { in: userIds } }, { eventId: { in: eventIds } }],
      },
    })
    const events = await tx.event.deleteMany({ where: { id: { in: eventIds } } })
    const sessions = await tx.session.deleteMany({ where: { userId: { in: userIds } } })
    const signIns = await tx.signInRequest.deleteMany({ where: { userId: { in: userIds } } })
    const apps = await tx.organizerApplication.deleteMany({
      where: { OR: [{ userId: { in: userIds } }, { reviewedById: { in: userIds } }] },
    })
    const deletedUsers = await tx.user.deleteMany({ where: { id: { in: userIds } } })

    return {
      bids: bids.count,
      auctions: auctions.count,
      listings: listings.count,
      gifts: gifts.count,
      redemptions: redemptions.count,
      transfers: transfers.count,
      tickets: tickets.count,
      mintRequests: mints.count,
      staff: staff.count,
      events: events.count,
      sessions: sessions.count,
      signInRequests: signIns.count,
      applications: apps.count,
      users: deletedUsers.count,
    }
  })

  console.log('\ndeleted:')
  for (const [k, v] of Object.entries(counts)) {
    if (v > 0) console.log(`  ${k.padEnd(16)} ${v}`)
  }
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(async () => {
    await disconnectLedger()
    await prisma.$disconnect()
  })
